# Level 1 - Yoshi's Island
#
# Doel:
# Verbind het Mushroom Kingdom met Yoshi's Island
#
# Daadwerkelijk doel:
# - pipeline laten starten
# - project laten builen
name: Level 1 - Yoshi's Island
on: # TODO - wanneer moet deze pipeline starten?
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code (Mario springt in zo'n groene pijp)
        uses: actions/checkout@v6

      - name: Setup Java 21
        uses: # TODO - Configureer JDK 21 - hint: wellicht ook iets met actions?
        with:
          java-version: '21'
          distribution: # TODO - Kies je favoriet - hint: 'temurin'

      - name: Setup Gradle
        uses: # TODO - Configureer Gradle

      - name: Build with Gradle (Build the castle)
        uses: # TODO - Run een gradle build commando - hint: ./gradlew ...